Fix undefined reference to pthread issues
* The pthreads library was not linked to compiling failed on some
systems with an "QoreThreadLocalStorage.h:73: undefined reference to `pthread_key_delete'" error
* Align minimum qore version inside README with the one required in the
CMakeLists.txt